[project]
name = "sass-example"
version = "1.0.0"
description = "Jac client application: sass-example"
entry-point = "main.jac"

[plugins.client]
# Vite bundler configuration (optional overrides)
# vite.plugins = []
# vite.build = {}

[dependencies.npm.dev]
sass = "^1.77.8"
