[project]
name = "pure-css"
version = "1.0.0"
description = "Jac client application: pure-css"
entry-point = "main.jac"

[plugins.client]
# Vite bundler configuration (optional overrides)
# vite.plugins = []
# vite.build = {}

[dependencies.npm]
"jac-client-node" = "1.0.4"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"
